name: CI

on:
  pull_request:
  workflow_dispatch: # manual run
  workflow_call:
    outputs:
      VERSTRING:
        description: Version string
        value: ${{ jobs.build.outputs.VERSTRING }}

jobs:
  build:
    name: Build boot.firm
    runs-on: ubuntu-latest
    outputs:
      VERSTRING: ${{ steps.verstring.outputs.VERSTRING }}
    container:
      image: leddaz/devkitarm
      options: --user 1001 # runner user, for git safedir
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: recursive # we currently don't use submodules, but just in case...
        fetch-depth: 0 # deep clone (for git describe)
        fetch-tags: true
    - name: Set version string
      id: verstring
      run: |
        VERSTRING=$(git describe --tags --match "v[0-9]*" --abbrev=7 | sed 's/-[0-9]*-g/-/')
        echo "VERSTRING=$VERSTRING" | tee -a $GITHUB_OUTPUT
    - name: Get additional dependencies
      run: python3 -m venv .venv && .venv/bin/pip install -U git+https://github.com/TuxSH/firmtool.git
    - name: Build
      run: make -j$(nproc --all)
    - name: Publish boot.firm (only on manual run or release)
      uses: actions/upload-artifact@v4
      with:
        # This produces a zip with boot.firm inside for security reasons
        # For publish_release this is presented as boot.firm however
        name: Luma3DS-${{ steps.verstring.outputs.VERSTRING }}
        path: boot.firm
